# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/cxx/WD_BLACK/qt_kaifa/pylight/ui/ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop.setGeometry(QtCore.QRect(20, 10, 121, 61))
        self.pushButton_stop.setStyleSheet(
    "QPushButton {\n"
    "    background-color: #4CAF50; /* Green */\n"
    "    border: 2px solid #4CAF50;\n"
    "    border-radius: 10px;\n"
    "    color: white;\n"
    "    padding: 15px 32px;\n"
    "    text-align: center;\n"
    "    text-decoration: none;\n"
    "    font-size: 20px;\n"
    "    margin: 4px 2px;\n"
    "}\n"
    "\n"
    "QPushButton:hover {\n"
    "    background-color: #45a049; /* Darker Green */\n"
    "}\n"
    "\n"
    "QPushButton:pressed {\n"
    "    background-color: #2980B9; /* Blue */\n"
    "}"
)
        self.pushButton_stop.setObjectName("pushButton_stop")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_stop.setText(_translate("MainWindow", "制动"))
